# Generated by Django 4.2 on 2025-06-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome_usuario", models.CharField(max_length=150)),
                ("email_usuario", models.EmailField(max_length=100, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("gamemaster", "Administrador"),
                            ("lider_grupo", "CEO do Grupo"),
                            ("membro_grupo", "Membro do Grupo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_usuario", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "USUARIOS",
            },
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("distancia_km", models.PositiveIntegerField()),
                ("demanda", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "db_table": "CIDADES",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("custo_producao", "Custo de Produção"),
                            ("custo_transporte", "Custo de Transporte"),
                            ("demanda", "Demanda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("impacto_percentual", models.IntegerField()),
                ("probabilidade", models.FloatField(default=0)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "EVENTOS",
            },
        ),
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estoque_inicial", models.PositiveIntegerField(default=0)),
                ("produtos_habilitados", models.TextField(blank=True)),
                ("modulo_producao", models.BooleanField(default=True)),
                ("modulo_distribuicao", models.BooleanField(default=True)),
                ("modulo_financeiro", models.BooleanField(default=True)),
                ("regra_eventos", models.JSONField(blank=True, default=dict)),
                ("maquinas_iniciais", models.PositiveIntegerField(default=1)),
                ("capacidade_maquina", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Configuração do Jogo",
                "verbose_name_plural": "Configurações do Jogo",
                "db_table": "CONFIG",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estoque", models.PositiveIntegerField(default=0)),
                ("maquinas", models.PositiveIntegerField(default=1)),
                ("capacidade_maquina", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "GRUPOS",
            },
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos",
                        to="app.gameconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogo",
                "verbose_name_plural": "Jogos",
                "db_table": "JOGOS",
            },
        ),
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fim", models.DateTimeField()),
                ("fechada", models.BooleanField(default=False)),
                (
                    "jogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodadas",
                        to="app.jogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
                "db_table": "RODADAS",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "receita",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lucro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_caixa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Financeiro",
                "verbose_name_plural": "Resultados Financeiros",
                "db_table": "FINANCEIRO",
                "ordering": ["rodada"],
            },
        ),
        migrations.CreateModel(
            name="Investimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(default=1)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("maquinas", "Aquisição de Máquinas"),
                            ("rh", "Recursos Humanos"),
                            ("financeiro", "Aplicações Financeiras"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investimentos",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investimento",
                "verbose_name_plural": "Investimentos",
                "db_table": "INVESTIMENTOS",
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="grupo",
            name="jogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="app.jogo",
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(
                related_name="grupos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EventoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(unique=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodadas",
                        to="app.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Rodada",
                "verbose_name_plural": "Eventos da Rodada",
                "db_table": "EVENTOS_RODADA",
                "ordering": ["rodada"],
            },
        ),
        migrations.CreateModel(
            name="Distribuicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(default=1)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "custo_transporte",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cidade"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuição",
                "verbose_name_plural": "Distribuições",
                "db_table": "DISTRIBUICOES",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="Decisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("quantidade", models.IntegerField(default=0)),
                ("resultado", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisão",
                "verbose_name_plural": "Decisões",
                "db_table": "DECISOES",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
