# Generated by Django 4.2 on 2025-06-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("receita", models.DecimalField(decimal_places=2, max_digits=12)),
                ("despesas", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "verbose_name": "Resultado Financeiro",
                "verbose_name_plural": "Resultados Financeiros",
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=100)),
                ("praca", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "promocao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Preço",
                "verbose_name_plural": "Preços",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("produto", models.CharField(max_length=100)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("praca", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
            },
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("distancia_km", models.PositiveIntegerField()),
                ("custo_por_km", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Rota de Transporte",
                "verbose_name_plural": "Rotas de Transporte",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="senha_usuario",
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(max_length=100)),
                ("pontuacao", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.financialresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
            },
        ),
    ]
