# Generated by Django 4.2 on 2025-06-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
                "db_table": "RODADAS",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="senha_usuario",
        ),
        migrations.CreateModel(
            name="ResultadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receita",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "despesas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fluxo_caixa_entrada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fluxo_caixa_saida",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lucro_liquido",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "fluxo_caixa_liquido",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "rodada",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado_financeiro",
                        to="app.rodada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Financeiro",
                "verbose_name_plural": "Resultados Financeiros",
                "db_table": "RESULTADOS_FINANCEIROS",
            },
        ),
    ]
