# Generated by Django 4.2 on 2025-06-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="senha_usuario",
        ),
    ]
