# Generated by Django 4.2 on 2025-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capital_inicial", models.PositiveIntegerField(default=0)),
                ("estoque_inicial", models.PositiveIntegerField(default=0)),
                ("produtos_habilitados", models.CharField(blank=True, max_length=255)),
                ("modulo_producao", models.BooleanField(default=True)),
                ("modulo_distribuicao", models.BooleanField(default=True)),
                ("modulo_financeiro", models.BooleanField(default=True)),
                ("modulo_eventos", models.BooleanField(default=True)),
                ("regras_eventos", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Configuração do Jogo",
                "verbose_name_plural": "Configurações do Jogo",
                "db_table": "CONFIGURACAO_JOGO",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="senha_usuario",
        ),
    ]
