# Generated by Django 4.2 on 2025-06-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "capacidade_por_hora",
                    models.PositiveIntegerField(
                        help_text="Unidades produzidas por hora"
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
                "db_table": "MAQUINAS",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("estoque_minimo", models.PositiveIntegerField(default=0)),
                ("estoque_maximo", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "PRODUTOS",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="senha_usuario",
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.maquina"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.produto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produção",
                "verbose_name_plural": "Produções",
                "db_table": "PRODUCOES",
            },
        ),
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=7,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento de Estoque",
                "verbose_name_plural": "Movimentos de Estoque",
                "db_table": "MOVIMENTOS_ESTOQUE",
            },
        ),
    ]
