# Generated by Django 4.2 on 2025-06-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_financialresult_pricelist_sale_transportroute_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("probabilidade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("impacto", models.TextField()),
            ],
            options={
                "verbose_name": "Evento Aleatório",
                "verbose_name_plural": "Eventos Aleatórios",
            },
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("data_ocorrencia", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.randomevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Evento",
                "verbose_name_plural": "Históricos de Eventos",
            },
        ),
    ]
