# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_create_initial_gamemaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("gamemaster", "Administrador"),
                    ("lider_grupo", "CEO do Grupo"),
                    ("membro_grupo", "Membro do Grupo"),
                ],
                default="membro_grupo",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Materia-Prima",
                "verbose_name_plural": "Materias-Primas",
                "db_table": "MATERIAS_PRIMAS",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("perecivel", models.BooleanField(default=False)),
                ("validade_rodadas", models.PositiveIntegerField(default=0)),
                ("tempo_producao_min", models.PositiveIntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "PRODUTOS",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ComposicaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_por_unidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes",
                        to="app.materiaprima",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composicao de Produto",
                "verbose_name_plural": "Composicoes de Produto",
                "db_table": "PRODUTO_COMPOSICAO",
            },
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("quantidade_planejada", models.PositiveIntegerField()),
                ("quantidade_produzida", models.PositiveIntegerField(default=0)),
                ("custo_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("custo_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producoes",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producoes",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producao",
                "verbose_name_plural": "Producoes",
                "db_table": "PRODUCOES",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.AddConstraint(
            model_name="composicaoproduto",
            constraint=models.UniqueConstraint(
                fields=("produto", "materia_prima"),
                name="uniq_composicao_produto_materia_prima",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisao",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"),
                name="uniq_decisao_grupo_rodada",
            ),
        ),
        migrations.AddConstraint(
            model_name="producao",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto", "rodada"),
                name="uniq_producao_grupo_produto_rodada",
            ),
        ),
        migrations.AddConstraint(
            model_name="rodada",
            constraint=models.UniqueConstraint(
                fields=("jogo", "numero"),
                name="uniq_rodada_numero_por_jogo",
            ),
        ),
    ]
