# Generated by Django 4.2 on 2025-06-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_create_initial_gamemaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig",
            name="numero_rodadas",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="capital_inicial",
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="maquinas_iniciais",
            field=models.PositiveIntegerField(default=40),
        ),
    ]
