# Generated by Django 4.2 on 2025-06-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_user_senha_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estoque_inicial", models.PositiveIntegerField(default=0)),
                ("produtos_habilitados", models.TextField(blank=True)),
                ("modulo_producao", models.BooleanField(default=True)),
                ("modulo_distribuicao", models.BooleanField(default=True)),
                ("modulo_financeiro", models.BooleanField(default=True)),
                ("regra_eventos", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Configuração do Jogo",
                "verbose_name_plural": "Configurações do Jogo",
                "db_table": "CONFIG",
            },
        ),
    ]
