# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_round_control_and_producao_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada_pedido", models.PositiveIntegerField()),
                ("rodada_recebimento", models.PositiveIntegerField()),
                ("quantidade_kg", models.DecimalField(decimal_places=2, max_digits=14)),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("custo_logistico", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("recebida", models.BooleanField(default=False)),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "cidade_fornecedora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_materia_prima",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_materia_prima",
                        to="app.grupo",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="app.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra de Materia-Prima",
                "verbose_name_plural": "Compras de Materia-Prima",
                "db_table": "COMPRAS_MATERIA_PRIMA",
                "ordering": ["-data_compra"],
            },
        ),
        migrations.CreateModel(
            name="EstoqueMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_kg", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques_materia_prima",
                        to="app.grupo",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Materia-Prima",
                "verbose_name_plural": "Estoques de Materias-Primas",
                "db_table": "ESTOQUES_MATERIA_PRIMA",
            },
        ),
        migrations.AddConstraint(
            model_name="estoquemateriaprima",
            constraint=models.UniqueConstraint(
                fields=("grupo", "materia_prima"),
                name="uniq_estoque_materia_prima_grupo",
            ),
        ),
    ]
