# Generated by Django 4.2 on 2025-06-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_group_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="producao",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="decision",
            name="venda",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProductionSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maquinas", models.PositiveIntegerField(default=1)),
                ("capacidade_maquina", models.PositiveIntegerField(default=100)),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producao_config",
                        to="app.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Produção",
                "verbose_name_plural": "Configurações de Produção",
                "db_table": "CONFIG_PRODUCAO",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=100)),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque",
                        to="app.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Estoque",
                "verbose_name_plural": "Itens de Estoque",
                "db_table": "ESTOQUE",
            },
        ),
    ]
