# Generated by Django 4.2 on 2025-06-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_grupo_resultadofinanceiro_grupo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoAleatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "probabilidade",
                    models.FloatField(help_text="Probabilidade de 0 a 1"),
                ),
            ],
            options={
                "verbose_name": "Evento Aleatório",
                "verbose_name_plural": "Eventos Aleatórios",
                "db_table": "EVENTOS_ALEATORIOS",
            },
        ),
        migrations.CreateModel(
            name="RegistroEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aplicacao", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.eventoaleatorio",
                    ),
                ),
                (
                    "rodada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.rodada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Evento",
                "verbose_name_plural": "Registros de Eventos",
                "db_table": "REGISTRO_EVENTOS",
            },
        ),
    ]
