# Generated by Django 4.2 on 2025-06-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_gameconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estoque", models.PositiveIntegerField(default=0)),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="grupos", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "GRUPOS",
            },
        ),
        migrations.CreateModel(
            name="Decisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("resultado", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisão",
                "verbose_name_plural": "Decisões",
                "db_table": "DECISOES",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
