# Generated by Django 4.2 on 2025-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_update_config_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventorodada",
            name="rodada",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="eventorodada",
            unique_together={("rodada", "evento")},
        ),
    ]
