# Generated by Django 4.2 on 2025-06-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_grupo_decisao"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisao",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gameconfig",
            name="capacidade_maquina",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="gameconfig",
            name="maquinas_iniciais",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="grupo",
            name="capacidade_maquina",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="grupo",
            name="maquinas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
