# Generated by Django 4.2 on 2025-06-06 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_add_evento_aleatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="rodada",
            name="data_fim",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rodada",
            name="data_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rodada",
            name="encerrada",
            field=models.BooleanField(default=False),
        ),
    ]
