# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_materia_prima_inventory_and_purchase_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada_entrada", models.PositiveIntegerField()),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques_produto",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Produto",
                "verbose_name_plural": "Estoques de Produtos",
                "db_table": "ESTOQUES_PRODUTO",
                "ordering": ["rodada_entrada", "id"],
            },
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distribuicoes",
                to="app.produto",
            ),
        ),
        migrations.AddConstraint(
            model_name="estoqueproduto",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto", "rodada_entrada"),
                name="uniq_estoque_produto_por_rodada",
            ),
        ),
    ]
