# Generated by Django 4.2 on 2025-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_allow_multiple_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig",
            name="trabalhadores_iniciais",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="grupo",
            name="trabalhadores",
            field=models.PositiveIntegerField(default=80),
        ),
    ]
