# Generated by Django 4.2 on 2025-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_allow_multiple_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig",
            name="trabalhadores_iniciais",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="grupo",
            name="funcionarios",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
