# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_product_inventory_and_distribution_by_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribuicao",
            name="processada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="quantidade_sobra",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="quantidade_vendida",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="receita_realizada",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
