# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_sales_processing_fields_on_distribuicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig",
            name="ranking_pesos",
            field=models.JSONField(
                blank=True,
                default={
                    "lucro": 0.4,
                    "market_share": 0.3,
                    "atendimento": 0.2,
                    "eficiencia_estoque": 0.1,
                },
            ),
        ),
        migrations.CreateModel(
            name="IndicadorRodadaGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("lucro_rodada", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("market_share_percent", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                (
                    "atendimento_demanda_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "eficiencia_estoque_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("score_multicriterio", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores_rodada",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador da Rodada por Grupo",
                "verbose_name_plural": "Indicadores da Rodada por Grupo",
                "db_table": "INDICADORES_RODADA_GRUPO",
                "ordering": ["rodada", "-score_multicriterio"],
            },
        ),
        migrations.CreateModel(
            name="MarketShareCidadeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("quantidade_vendida", models.PositiveIntegerField(default=0)),
                ("market_share_percent", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Share Cidade Produto",
                "verbose_name_plural": "Market Shares Cidade Produto",
                "db_table": "MARKET_SHARE_CIDADE_PRODUTO",
            },
        ),
        migrations.AddConstraint(
            model_name="indicadorrodadagrupo",
            constraint=models.UniqueConstraint(fields=("grupo", "rodada"), name="uniq_indicador_grupo_rodada"),
        ),
        migrations.AddConstraint(
            model_name="marketsharecidadeproduto",
            constraint=models.UniqueConstraint(
                fields=("grupo", "cidade", "produto", "rodada"),
                name="uniq_market_share_cidade_produto_rodada",
            ),
        ),
    ]
