# Generated by Django 4.2 on 2025-08-21 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_machine_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="lider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_liderados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
