# Generated by Django 4.2 on 2025-06-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_sprint5_distribuicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribuicao",
            name="rodada",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ResultadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "receita",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lucro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_caixa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Financeiro",
                "verbose_name_plural": "Resultados Financeiros",
                "db_table": "FINANCEIRO",
                "ordering": ["rodada"],
            },
        ),
    ]
