# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_market_share_and_multicriteria_ranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacidadeProdutoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maquinas", models.PositiveIntegerField(default=0)),
                ("minutos_por_maquina", models.PositiveIntegerField(default=400)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_produto",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_grupo",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidade por Produto do Grupo",
                "verbose_name_plural": "Capacidades por Produto do Grupo",
                "db_table": "CAPACIDADE_PRODUTO_GRUPO",
            },
        ),
        migrations.AddConstraint(
            model_name="capacidadeprodutogrupo",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto"), name="uniq_capacidade_grupo_produto"
            ),
        ),
    ]
