# Generated by Django 4.2 on 2025-06-07 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_sprint6_financeiro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("custo_producao", "Custo de Produção"),
                            ("custo_transporte", "Custo de Transporte"),
                            ("demanda", "Demanda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("impacto_percentual", models.IntegerField()),
                ("probabilidade", models.FloatField(default=0)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "EVENTOS",
            },
        ),
        migrations.CreateModel(
            name="EventoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(unique=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodadas",
                        to="app.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Rodada",
                "verbose_name_plural": "Eventos da Rodada",
                "db_table": "EVENTOS_RODADA",
                "ordering": ["rodada"],
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model("app", "Evento").objects.create(
                    nome="Aumento do combustível",
                    tipo="custo_transporte",
                    impacto_percentual=20,
                    probabilidade=0.4,
                    descricao="Custos de transporte +20%",
                ),
                apps.get_model("app", "Evento").objects.create(
                    nome="Subsídio à produção",
                    tipo="custo_producao",
                    impacto_percentual=-15,
                    probabilidade=0.3,
                    descricao="Custos de produção -15%",
                ),
                apps.get_model("app", "Evento").objects.create(
                    nome="Demanda aquecida",
                    tipo="demanda",
                    impacto_percentual=25,
                    probabilidade=0.3,
                    descricao="Aumento de 25% na demanda",
                ),
            ],
            lambda apps, schema_editor: apps.get_model("app", "Evento").objects.all().delete(),
        ),
    ]
