# Generated by Django 4.2 on 2025-06-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_sprint7_eventos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fim", models.DateTimeField()),
                ("fechada", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
                "db_table": "RODADAS",
                "ordering": ["numero"],
            },
        ),
    ]
