# Generated by Django 4.2 on 2026-03-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_capacidade_produto_grupo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidadoRodadaGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "receita_vendas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos_operacionais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "penalidade_sem_submissao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "perda_pereciveis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_armazenagem_mp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_armazenagem_produtos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos_totais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lucro_rodada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_caixa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_ofertado", models.PositiveIntegerField(default=0)),
                ("total_vendido", models.PositiveIntegerField(default=0)),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "atendimento_demanda_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "eficiencia_estoque_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "score_multicriterio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidados_rodada",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidado da Rodada por Grupo",
                "verbose_name_plural": "Consolidados da Rodada por Grupo",
                "db_table": "CONSOLIDADO_RODADA_GRUPO",
                "ordering": ["-rodada", "grupo__nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="consolidadorodadagrupo",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_consolidado_grupo_rodada"
            ),
        ),
    ]
