# Generated by Django 4.2 on 2026-03-09 14:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_consolidado_rodada_grupo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decisao",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Decisao",
                "verbose_name_plural": "Decisoes",
            },
        ),
        migrations.AlterModelOptions(
            name="distribuicao",
            options={
                "ordering": ["-data_envio"],
                "verbose_name": "Distribuicao",
                "verbose_name_plural": "Distribuicoes",
            },
        ),
        migrations.AlterModelOptions(
            name="gameconfig",
            options={
                "verbose_name": "Configuracao do Jogo",
                "verbose_name_plural": "Configuracoes do Jogo",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("custo_producao", "Custo de Producao"),
                    ("custo_transporte", "Custo de Transporte"),
                    ("demanda", "Demanda"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="ranking_pesos",
            field=models.JSONField(
                blank=True, default=app.models.default_ranking_pesos
            ),
        ),
        migrations.AlterField(
            model_name="investimento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("marketing", "Marketing"),
                    ("maquinas", "Aquisicao de Maquinas"),
                    ("rh", "Recursos Humanos"),
                    ("financeiro", "Aplicacoes Financeiras"),
                ],
                max_length=20,
            ),
        ),
    ]
