# Generated by Django 4.2 on 2025-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_maquina_produto_remove_user_senha_usuario_producao_and_more"),
        ("app", "0005_rodada_data_fim_rodada_data_inicio_rodada_encerrada"),
        ("app", "0009_sprint8_fechamento"),
    ]

    operations = []
