# Generated by Django 4.2 on 2025-08-29 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_resultadofinanceiro_penalidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribuicao",
            name="fator_marketing",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="qualidade",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name="distribuicao",
            name="vendas_realizadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="investimento",
            name="cidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investimentos",
                to="app.cidade",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("custo_producao", "Custo de Produção"),
                    ("custo_transporte", "Custo de Transporte"),
                    ("demanda", "Demanda"),
                    ("perda_estoque", "Perda de Estoque"),
                    ("greve", "Greve"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="app.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "PRODUTOS",
            },
        ),
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias_primas",
                        to="app.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias_primas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria Prima",
                "verbose_name_plural": "Matérias Primas",
                "db_table": "MATERIAS_PRIMAS",
            },
        ),
        migrations.CreateModel(
            name="EstoqueDetalhado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("custo_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.produto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_estoque",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque Detalhado",
                "verbose_name_plural": "Estoques Detalhados",
                "db_table": "ESTOQUE_DETALHADO",
            },
        ),
        migrations.CreateModel(
            name="VendaCidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("quantidade_vendida", models.PositiveIntegerField(default=0)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas_cidade",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas_cidade",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda por Cidade",
                "verbose_name_plural": "Vendas por Cidade",
                "db_table": "VENDAS_CIDADE",
                "unique_together": {("grupo", "cidade", "rodada")},
            },
        ),
    ]
