# Generated by Django 4.2 on 2026-03-09 14:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_decisao_options_alter_distribuicao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AplicacaoFinanceiraGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_aplicado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxa_juros_rodada",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.015"), max_digits=6
                    ),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aplicacao Financeira do Grupo",
                "verbose_name_plural": "Aplicacoes Financeiras dos Grupos",
                "db_table": "APLICACAO_FINANCEIRA_GRUPO",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaSubmissaoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Auditoria de Submissao da Rodada",
                "verbose_name_plural": "Auditorias de Submissao da Rodada",
                "db_table": "AUDITORIA_SUBMISSAO_RODADA",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="CEOGrupoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CEO do Grupo por Rodada",
                "verbose_name_plural": "CEOs do Grupo por Rodada",
                "db_table": "CEO_GRUPO_RODADA",
                "ordering": ["-rodada", "grupo__nome"],
            },
        ),
        migrations.CreateModel(
            name="DemandaCidadeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demanda_maxima", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Demanda por Cidade e Produto",
                "verbose_name_plural": "Demandas por Cidade e Produto",
                "db_table": "DEMANDA_CIDADE_PRODUTO",
            },
        ),
        migrations.CreateModel(
            name="ExecucaoJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comando", models.CharField(max_length=120)),
                ("correlation_id", models.CharField(db_index=True, max_length=40)),
                ("rodada", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sucesso", "Sucesso"), ("falha", "Falha")],
                        default="sucesso",
                        max_length=20,
                    ),
                ),
                ("detalhes", models.TextField(blank=True)),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Execucao de Job",
                "verbose_name_plural": "Execucoes de Jobs",
                "db_table": "EXECUCAO_JOBS",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.AddField(
            model_name="capacidadeprodutogrupo",
            name="operadores",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compramateriaprima",
            name="desconto_logistico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="evento",
            name="duracao_rodadas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="evento",
            name="efeito_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("atraso_mp", "Atraso de Materia-Prima"),
                    ("retencao_entrega", "Retencao de Entregas"),
                    ("bloqueio_producao", "Bloqueio de Producao"),
                    ("quebra_estoque", "Quebra de Estoque"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="modo_aplicacao",
            field=models.CharField(
                choices=[("percentual", "Percentual"), ("estado", "Estado")],
                default="percentual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventorodada",
            name="jogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_rodada",
                to="app.jogo",
            ),
        ),
        migrations.AddField(
            model_name="investimento",
            name="cidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investimentos",
                to="app.cidade",
            ),
        ),
        migrations.AddField(
            model_name="investimento",
            name="operacao_financeira",
            field=models.CharField(
                choices=[("aplicar", "Aplicar"), ("resgatar", "Resgatar")],
                default="aplicar",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investimento",
            name="processado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="investimento",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investimentos",
                to="app.produto",
            ),
        ),
        migrations.AddField(
            model_name="investimento",
            name="quantidade",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="investimento",
            name="rodada_ativacao",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="eventorodada",
            name="rodada",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="eventorodada",
            constraint=models.UniqueConstraint(
                fields=("jogo", "rodada"), name="uniq_evento_rodada_por_jogo"
            ),
        ),
        migrations.AddField(
            model_name="demandacidadeproduto",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandas_produto",
                to="app.cidade",
            ),
        ),
        migrations.AddField(
            model_name="demandacidadeproduto",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandas_cidade",
                to="app.produto",
            ),
        ),
        migrations.AddField(
            model_name="ceogruporodada",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceos_rodada",
                to="app.grupo",
            ),
        ),
        migrations.AddField(
            model_name="ceogruporodada",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ceo_rodadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditoriasubmissaorodada",
            name="decisao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditorias",
                to="app.decisao",
            ),
        ),
        migrations.AddField(
            model_name="auditoriasubmissaorodada",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditorias_submissao",
                to="app.grupo",
            ),
        ),
        migrations.AddField(
            model_name="auditoriasubmissaorodada",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditorias_submissao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aplicacaofinanceiragrupo",
            name="grupo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aplicacao_financeira",
                to="app.grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandacidadeproduto",
            constraint=models.UniqueConstraint(
                fields=("cidade", "produto"), name="uniq_demanda_cidade_produto"
            ),
        ),
        migrations.AddConstraint(
            model_name="ceogruporodada",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_ceo_grupo_rodada"
            ),
        ),
    ]
