# Generated by Django 4.2 on 2025-08-29 14:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_distribuicao_fator_marketing_distribuicao_qualidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("prazo_entrega", models.PositiveIntegerField()),
                (
                    "custo_logistico_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.50"), max_digits=10
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fornecedores",
                        to="app.cidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "FORNECEDORES",
            },
        ),
        migrations.CreateModel(
            name="PedidoMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("prazo_entrega", models.PositiveIntegerField()),
                (
                    "custo_logistico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="app.fornecedor",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_materia_prima",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Matéria-Prima",
                "verbose_name_plural": "Pedidos de Matéria-Prima",
                "db_table": "PEDIDOS_MATERIA_PRIMA",
            },
        ),
    ]
