# Generated by Django 4.2 on 2025-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_fornecedor_pedidomateriaprima"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="custo_producao",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="produto",
            name="materias_primas",
            field=models.ManyToManyField(
                blank=True, related_name="produtos", to="app.materiaprima"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="validade",
            field=models.DateField(blank=True, null=True),
        ),
    ]
