# Generated by Django 4.2 on 2025-08-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_produto_custo_producao_produto_materias_primas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinhaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidade", models.PositiveIntegerField(default=0)),
                ("maquinas", models.PositiveIntegerField(default=0)),
                ("mao_de_obra", models.PositiveIntegerField(default=0)),
                ("producao", models.PositiveIntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linhas_producao",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Produção",
                "verbose_name_plural": "Linhas de Produção",
                "db_table": "LINHAS_PRODUCAO",
            },
        ),
    ]
