# Generated by Django 4.2 on 2025-08-29
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_linhaproducao"),
    ]

    operations = [
        migrations.AddField(
            model_name="investimento",
            name="roi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="investimento",
            name="tempo_maturacao",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="investimento",
            name="retorno_aplicado",
            field=models.BooleanField(default=False),
        ),
    ]
