# Generated by Django 4.2 on 2026-03-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_aplicacaofinanceiragrupo_auditoriasubmissaorodada_and_more"),
        ("app", "0014_investimento_fields"),
    ]

    operations = []
