# Generated by Django 4.2 on 2026-03-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_merge_20260309_1505"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Mercado",
                "verbose_name_plural": "Mercados",
                "db_table": "MERCADOS",
            },
        ),
        migrations.RemoveField(
            model_name="fornecedor",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="pedidomateriaprima",
            name="fornecedor",
        ),
        migrations.RemoveField(
            model_name="pedidomateriaprima",
            name="grupo",
        ),
        migrations.AlterUniqueTogether(
            name="vendacidade",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vendacidade",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="vendacidade",
            name="grupo",
        ),
        migrations.AlterUniqueTogether(
            name="eventorodada",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="distribuicao",
            name="fator_marketing",
        ),
        migrations.RemoveField(
            model_name="distribuicao",
            name="qualidade",
        ),
        migrations.RemoveField(
            model_name="distribuicao",
            name="vendas_realizadas",
        ),
        migrations.AddField(
            model_name="cidade",
            name="limite_demanda",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("custo_producao", "Custo de Producao"),
                    ("custo_transporte", "Custo de Transporte"),
                    ("demanda", "Demanda"),
                    ("perda_estoque", "Perda de Estoque"),
                    ("greve", "Greve"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="EstoqueDetalhado",
        ),
        migrations.DeleteModel(
            name="Fornecedor",
        ),
        migrations.DeleteModel(
            name="PedidoMateriaPrima",
        ),
        migrations.DeleteModel(
            name="VendaCidade",
        ),
        migrations.AddField(
            model_name="cidade",
            name="mercado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cidades",
                to="app.mercado",
            ),
        ),
    ]
