# Generated by Django 4.2 on 2026-03-09 18:46

import app.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome_usuario", models.CharField(max_length=150)),
                ("email_usuario", models.EmailField(max_length=100, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("gamemaster", "Administrador"),
                            ("lider_grupo", "CEO do Grupo"),
                            ("membro_grupo", "Membro do Grupo"),
                        ],
                        default="membro_grupo",
                        max_length=20,
                    ),
                ),
                ("status_usuario", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "USUARIOS",
            },
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("distancia_km", models.PositiveIntegerField()),
                ("demanda", models.PositiveIntegerField(default=0)),
                ("limite_demanda", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "db_table": "CIDADES",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("custo_producao", "Custo de Producao"),
                            ("custo_transporte", "Custo de Transporte"),
                            ("demanda", "Demanda"),
                            ("perda_estoque", "Perda de Estoque"),
                            ("greve", "Greve"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modo_aplicacao",
                    models.CharField(
                        choices=[("percentual", "Percentual"), ("estado", "Estado")],
                        default="percentual",
                        max_length=20,
                    ),
                ),
                (
                    "efeito_estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("atraso_mp", "Atraso de Materia-Prima"),
                            ("retencao_entrega", "Retencao de Entregas"),
                            ("bloqueio_producao", "Bloqueio de Producao"),
                            ("quebra_estoque", "Quebra de Estoque"),
                        ],
                        max_length=30,
                    ),
                ),
                ("duracao_rodadas", models.PositiveIntegerField(default=1)),
                ("impacto_percentual", models.IntegerField()),
                ("probabilidade", models.FloatField(default=0)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "EVENTOS",
            },
        ),
        migrations.CreateModel(
            name="ExecucaoJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comando", models.CharField(max_length=120)),
                ("correlation_id", models.CharField(db_index=True, max_length=40)),
                ("rodada", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sucesso", "Sucesso"), ("falha", "Falha")],
                        default="sucesso",
                        max_length=20,
                    ),
                ),
                ("detalhes", models.TextField(blank=True)),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Execucao de Job",
                "verbose_name_plural": "Execucoes de Jobs",
                "db_table": "EXECUCAO_JOBS",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital_inicial",
                    models.DecimalField(
                        decimal_places=2, default=1000000, max_digits=12
                    ),
                ),
                ("estoque_inicial", models.PositiveIntegerField(default=0)),
                ("produtos_habilitados", models.TextField(blank=True)),
                ("modulo_producao", models.BooleanField(default=True)),
                ("modulo_distribuicao", models.BooleanField(default=True)),
                ("modulo_financeiro", models.BooleanField(default=True)),
                ("regra_eventos", models.JSONField(blank=True, default=dict)),
                (
                    "ranking_pesos",
                    models.JSONField(
                        blank=True, default=app.models.default_ranking_pesos
                    ),
                ),
                ("maquinas_iniciais", models.PositiveIntegerField(default=40)),
                ("maquinas_iniciais_a", models.PositiveIntegerField(default=15)),
                ("maquinas_iniciais_b", models.PositiveIntegerField(default=15)),
                ("maquinas_iniciais_c", models.PositiveIntegerField(default=10)),
                ("trabalhadores_iniciais", models.PositiveIntegerField(default=80)),
                ("capacidade_maquina", models.PositiveIntegerField(default=100)),
                (
                    "numero_rodadas",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracao do Jogo",
                "verbose_name_plural": "Configuracoes do Jogo",
                "db_table": "CONFIG",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estoque", models.PositiveIntegerField(default=0)),
                ("materia_prima", models.PositiveIntegerField(default=0)),
                ("maquinas", models.PositiveIntegerField(default=1)),
                ("maquinas_a", models.PositiveIntegerField(default=15)),
                ("maquinas_b", models.PositiveIntegerField(default=15)),
                ("maquinas_c", models.PositiveIntegerField(default=10)),
                ("trabalhadores", models.PositiveIntegerField(default=80)),
                ("capacidade_maquina", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "GRUPOS",
            },
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogos",
                        to="app.gameconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogo",
                "verbose_name_plural": "Jogos",
                "db_table": "JOGOS",
            },
        ),
        migrations.CreateModel(
            name="MateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Materia-Prima",
                "verbose_name_plural": "Materias-Primas",
                "db_table": "MATERIAS_PRIMAS",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Mercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Mercado",
                "verbose_name_plural": "Mercados",
                "db_table": "MERCADOS",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("perecivel", models.BooleanField(default=False)),
                ("validade_rodadas", models.PositiveIntegerField(default=0)),
                ("tempo_producao_min", models.PositiveIntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "PRODUTOS",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fim", models.DateTimeField()),
                ("fechada", models.BooleanField(default=False)),
                (
                    "jogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodadas",
                        to="app.jogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
                "db_table": "RODADAS",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "receita",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lucro",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_caixa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "penalidades",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado Financeiro",
                "verbose_name_plural": "Resultados Financeiros",
                "db_table": "FINANCEIRO",
                "ordering": ["rodada"],
            },
        ),
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("quantidade_planejada", models.PositiveIntegerField()),
                ("quantidade_produzida", models.PositiveIntegerField(default=0)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producoes",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producoes",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producao",
                "verbose_name_plural": "Producoes",
                "db_table": "PRODUCOES",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="MarketShareCidadeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("quantidade_vendida", models.PositiveIntegerField(default=0)),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_shares",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Share Cidade Produto",
                "verbose_name_plural": "Market Shares Cidade Produto",
                "db_table": "MARKET_SHARE_CIDADE_PRODUTO",
            },
        ),
        migrations.CreateModel(
            name="LinhaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidade", models.PositiveIntegerField(default=0)),
                ("maquinas", models.PositiveIntegerField(default=0)),
                ("mao_de_obra", models.PositiveIntegerField(default=0)),
                ("producao", models.PositiveIntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linhas_producao",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Produção",
                "verbose_name_plural": "Linhas de Produção",
                "db_table": "LINHAS_PRODUCAO",
            },
        ),
        migrations.CreateModel(
            name="Investimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(default=1)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("maquinas", "Aquisicao de Maquinas"),
                            ("rh", "Recursos Humanos"),
                            ("financeiro", "Aplicacoes Financeiras"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("roi", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("tempo_maturacao", models.PositiveIntegerField(default=1)),
                ("retorno_aplicado", models.BooleanField(default=False)),
                (
                    "operacao_financeira",
                    models.CharField(
                        choices=[("aplicar", "Aplicar"), ("resgatar", "Resgatar")],
                        default="aplicar",
                        max_length=20,
                    ),
                ),
                ("rodada_ativacao", models.PositiveIntegerField(default=1)),
                ("processado", models.BooleanField(default=False)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investimentos",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investimentos",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investimentos",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investimento",
                "verbose_name_plural": "Investimentos",
                "db_table": "INVESTIMENTOS",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="IndicadorRodadaGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "lucro_rodada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "atendimento_demanda_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "eficiencia_estoque_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "score_multicriterio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores_rodada",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador da Rodada por Grupo",
                "verbose_name_plural": "Indicadores da Rodada por Grupo",
                "db_table": "INDICADORES_RODADA_GRUPO",
                "ordering": ["rodada", "-score_multicriterio"],
            },
        ),
        migrations.AddField(
            model_name="grupo",
            name="jogo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="app.jogo",
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="lider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_liderados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="membros",
            field=models.ManyToManyField(
                related_name="grupos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EventoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rodadas",
                        to="app.evento",
                    ),
                ),
                (
                    "jogo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_rodada",
                        to="app.jogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Rodada",
                "verbose_name_plural": "Eventos da Rodada",
                "db_table": "EVENTOS_RODADA",
                "ordering": ["rodada"],
            },
        ),
        migrations.CreateModel(
            name="EstoqueProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada_entrada", models.PositiveIntegerField()),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques_produto",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Produto",
                "verbose_name_plural": "Estoques de Produtos",
                "db_table": "ESTOQUES_PRODUTO",
                "ordering": ["rodada_entrada", "id"],
            },
        ),
        migrations.CreateModel(
            name="EstoqueMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques_materia_prima",
                        to="app.grupo",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="app.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Materia-Prima",
                "verbose_name_plural": "Estoques de Materias-Primas",
                "db_table": "ESTOQUES_MATERIA_PRIMA",
            },
        ),
        migrations.CreateModel(
            name="Distribuicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField(default=1)),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "custo_transporte",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantidade_vendida", models.PositiveIntegerField(default=0)),
                ("quantidade_sobra", models.PositiveIntegerField(default=0)),
                (
                    "receita_realizada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("processada", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cidade"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribuicoes",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribuicao",
                "verbose_name_plural": "Distribuicoes",
                "db_table": "DISTRIBUICOES",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="DemandaCidadeProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demanda_maxima", models.PositiveIntegerField(default=0)),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandas_produto",
                        to="app.cidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandas_cidade",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demanda por Cidade e Produto",
                "verbose_name_plural": "Demandas por Cidade e Produto",
                "db_table": "DEMANDA_CIDADE_PRODUTO",
            },
        ),
        migrations.CreateModel(
            name="Decisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("quantidade", models.IntegerField(default=0)),
                ("resultado", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisoes",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisao",
                "verbose_name_plural": "Decisoes",
                "db_table": "DECISOES",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ConsolidadoRodadaGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                (
                    "receita_vendas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos_operacionais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "penalidade_sem_submissao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "perda_pereciveis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_armazenagem_mp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custo_armazenagem_produtos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "custos_totais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lucro_rodada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_caixa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_ofertado", models.PositiveIntegerField(default=0)),
                ("total_vendido", models.PositiveIntegerField(default=0)),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "atendimento_demanda_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "eficiencia_estoque_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "score_multicriterio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidados_rodada",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidado da Rodada por Grupo",
                "verbose_name_plural": "Consolidados da Rodada por Grupo",
                "db_table": "CONSOLIDADO_RODADA_GRUPO",
                "ordering": ["-rodada", "grupo__nome"],
            },
        ),
        migrations.CreateModel(
            name="CompraMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada_pedido", models.PositiveIntegerField()),
                ("rodada_recebimento", models.PositiveIntegerField()),
                ("quantidade_kg", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "custo_logistico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "desconto_logistico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("recebida", models.BooleanField(default=False)),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "cidade_fornecedora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras_materia_prima",
                        to="app.cidade",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_materia_prima",
                        to="app.grupo",
                    ),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="app.materiaprima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra de Materia-Prima",
                "verbose_name_plural": "Compras de Materia-Prima",
                "db_table": "COMPRAS_MATERIA_PRIMA",
                "ordering": ["-data_compra"],
            },
        ),
        migrations.CreateModel(
            name="ComposicaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_por_unidade",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes",
                        to="app.materiaprima",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicoes",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composicao de Produto",
                "verbose_name_plural": "Composicoes de Produto",
                "db_table": "PRODUTO_COMPOSICAO",
            },
        ),
        migrations.AddField(
            model_name="cidade",
            name="mercado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cidades",
                to="app.mercado",
            ),
        ),
        migrations.CreateModel(
            name="CEOGrupoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceos_rodada",
                        to="app.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceo_rodadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CEO do Grupo por Rodada",
                "verbose_name_plural": "CEOs do Grupo por Rodada",
                "db_table": "CEO_GRUPO_RODADA",
                "ordering": ["-rodada", "grupo__nome"],
            },
        ),
        migrations.CreateModel(
            name="CapacidadeProdutoGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maquinas", models.PositiveIntegerField(default=0)),
                ("operadores", models.PositiveIntegerField(default=0)),
                ("minutos_por_maquina", models.PositiveIntegerField(default=400)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_produto",
                        to="app.grupo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacidades_grupo",
                        to="app.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidade por Produto do Grupo",
                "verbose_name_plural": "Capacidades por Produto do Grupo",
                "db_table": "CAPACIDADE_PRODUTO_GRUPO",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaSubmissaoRodada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.PositiveIntegerField()),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "decisao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to="app.decisao",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditorias_submissao",
                        to="app.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_submissao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Submissao da Rodada",
                "verbose_name_plural": "Auditorias de Submissao da Rodada",
                "db_table": "AUDITORIA_SUBMISSAO_RODADA",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="AplicacaoFinanceiraGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_aplicado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxa_juros_rodada",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.015"), max_digits=6
                    ),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicacao_financeira",
                        to="app.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicacao Financeira do Grupo",
                "verbose_name_plural": "Aplicacoes Financeiras dos Grupos",
                "db_table": "APLICACAO_FINANCEIRA_GRUPO",
            },
        ),
        migrations.AddConstraint(
            model_name="rodada",
            constraint=models.UniqueConstraint(
                fields=("jogo", "numero"), name="uniq_rodada_numero_por_jogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="producao",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto", "rodada"),
                name="uniq_producao_grupo_produto_rodada",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketsharecidadeproduto",
            constraint=models.UniqueConstraint(
                fields=("grupo", "cidade", "produto", "rodada"),
                name="uniq_market_share_cidade_produto_rodada",
            ),
        ),
        migrations.AddConstraint(
            model_name="indicadorrodadagrupo",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_indicador_grupo_rodada"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventorodada",
            constraint=models.UniqueConstraint(
                fields=("jogo", "rodada"), name="uniq_evento_rodada_por_jogo"
            ),
        ),
        migrations.AddConstraint(
            model_name="estoqueproduto",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto", "rodada_entrada"),
                name="uniq_estoque_produto_por_rodada",
            ),
        ),
        migrations.AddConstraint(
            model_name="estoquemateriaprima",
            constraint=models.UniqueConstraint(
                fields=("grupo", "materia_prima"),
                name="uniq_estoque_materia_prima_grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandacidadeproduto",
            constraint=models.UniqueConstraint(
                fields=("cidade", "produto"), name="uniq_demanda_cidade_produto"
            ),
        ),
        migrations.AddConstraint(
            model_name="decisao",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_decisao_grupo_rodada"
            ),
        ),
        migrations.AddConstraint(
            model_name="consolidadorodadagrupo",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_consolidado_grupo_rodada"
            ),
        ),
        migrations.AddConstraint(
            model_name="composicaoproduto",
            constraint=models.UniqueConstraint(
                fields=("produto", "materia_prima"),
                name="uniq_composicao_produto_materia_prima",
            ),
        ),
        migrations.AddConstraint(
            model_name="ceogruporodada",
            constraint=models.UniqueConstraint(
                fields=("grupo", "rodada"), name="uniq_ceo_grupo_rodada"
            ),
        ),
        migrations.AddConstraint(
            model_name="capacidadeprodutogrupo",
            constraint=models.UniqueConstraint(
                fields=("grupo", "produto"), name="uniq_capacidade_grupo_produto"
            ),
        ),
    ]
